server:
    type: default
    applicationConnectors:
        -   type: http
            port: 8080
database:
  driverClass: org.h2.Driver
  user: sa
#  password:
  url: jdbc:h2:./build/efdb;AUTO_SERVER=TRUE
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
  properties:
    hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.show_sql: false
    hibernate.generate_statistics: false
    hibernate.hbm2ddl.auto: create
swagger:
  resourcePackage: com.macgregor.ef.resource
  title: endlessfrontier-api
  description: Unofficial rest service for accessing Endless Frontier data. Please submit issues to https://github.com/macgregor/endlessfrontier_api/issues
  version: v1
  contact: Matthew Stratton
  contactEmail: matthew.m.stratton@gmail.com
  contactUrl: https://github.com/macgregor
  license: MIT
  licenseUrl: https://opensource.org/licenses/MIT
  schemes: ['https', 'http']
logging:
  level: INFO
  loggers:
      "io.dropwizard": INFO
      "org.hibernate.SQL":
        level: ERROR
      "org.hibernate":
        level: ERROR
      "com.macgregor.ef":
        level: INFO
      "org.reflections":
        level: ERROR
      "org.eclipse.jetty":
        level: ERROR
      "com.macgregor.ef.dataload":
            level: DEBUG
            additive: false
            appenders:
              - type: file
                currentLogFilename: ./build/dataload.log
                archivedLogFilenamePattern: ./build/dataload-%d.log.gz
                archivedFileCount: 5
  appenders:
      - type: console