server:
    type: default
    applicationConnectors:
        -   type: http
            port: 8080
database:
  driverClass: org.h2.Driver
  user: sa
#  password:
  url: jdbc:h2:./persondb
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
  properties:
    hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.show_sql: true
    hibernate.generate_statistics: false
    hibernate.hbm2ddl.auto: validate # validates schema when service is started
swagger:
  resourcePackage: com.macgregor.ef.resource
  title: endlessfrontier-api
  version: v1
  contact: matthew.m.stratton@gmail.com
  license: MIT
  licenseUrl: https://opensource.org/licenses/MIT
logging:
  level: INFO