create table pet (
    id int not null,
    className varchar not null,
    name varchar not null,
    tribe int not null,
    type varchar not null,
    rank int not null,
    skill1 int not null,
    value1 varchar not null,
    skill2 int not null,
    value2 varchar not null,
    value3 varchar not null,
    master_skill int not null,
    couple int not null,
    inc_gold_level varchar not null,
    treasure int not null,
    is_percent varchar not null,
    is_alpha varchar not null
);